### ISSUE TITLE
Extension has no logo in the vscode marketplace

### ISSUE THREAD

**Issue by virejdasani** [hadll/PythOwO-VScode-language-support#3]
I didn't know this existed, thanks a lot for making this!

![image](https://user-images.githubusercontent.com/67495678/191231857-803e7c02-4862-4b1b-8dba-b92e766e4da0.png)

The extension would look way better with the pythowo icon.

**Comment by hadll** [comment]
Thanks for the feedback, There should be an icon in the live version now
